### ISSUE TITLE
Npcap documentation

### ISSUE THREAD

**Issue by dadodasyra** [shellrow/nex#6]
First, great project.

It seems that nex is not usable without npcap on Windows. I saw you were working on "nex-npcap-helper" which would be an automatic installer of npcap I guess ? 
Is it already a working thing ? How should it be used ? will it be fully silent ?

Btw maybe you should write in the readme that npcap is a dependency for windows.

**Comment by shellrow** [comment]
Thank you for your feedback!

You're correct. Npcap is essential for `nex`(`nex-datalink`) on Windows due to its ability to bypass Winsock limitations and handle L2 frames effectively. We chose Npcap because it's signed, actively maintained, and widely recognized in the community.

Regarding `nex-npcap-helper`, you're absolutely right. It's not completely silent due to Npcap's licensing constraints. The helper tool assists users by automating the download and execution of the Npcap installer. However, users will still need to interact with the installer GUI to complete the installation process.

The primary aim of `nex-npcap-helper` is to streamline the installation process for Npcap, providing support for users of `nex` library or application using `nex`, particularly on Windows environments.

Thank you for bringing up the importance of mentioning Npcap as a dependency in the README. We'll make sure to include that information for better clarity.
